# Run using `rustfmt --write-mode overwrite *.rs` in the
# root of the src directory. You may still get some
# formatting errors (whitespace etc) which should be
# fixed manually before committing.

# Max line length that will be parsed by rustfmt
max_width = 160

# Organise imports in a consistant way
reorder_imports = true
reorder_imported_names = true
reorder_imports_in_group = true

# This can sometimes break when comments include line breaks
wrap_comments = true

# Try to place function args on complete lines rather than
# as a vertical block
fn_args_density = "Compressed"

# Allow for compact formatting of struct literals
struct_field_align_threshold = 20

# Replace calls to the try! macro with ? syntax
use_try_shorthand = true
