# Run using `rustfmt --write-mode overwrite *.rs` in the
# root of the src directory. You may still get some
# formatting errors (whitespace etc) which should be
# fixed manually before committing.

# Max line length that will be parsed by rustfmt
max_width = 160

# Organise imports in a consistant way
reorder_imports = true
reorder_imported_names = true
reorder_imports_in_group = true

# This can sometimes break when comments include line breaks
wrap_comments = true

# Visually align chained method calls on `.`
# chain_indent = "Visual"
chain_indent = "Block"
chain_one_line_max = 60
chain_split_single_child = true

# Try to place function args on complete lines rather than
# as a vertical block
fn_args_density = "Compressed"

# Allow for compact formatting of struct literals
stuct_lit_width = 60
struct_variant_width = 60
struct_field_align_threshold = 20
struct_lit_multiline_style = "PreferSingle"

# Replace calls to the try! macro with ? syntax
use_try_shorthand = true

# Allow for full width function calls
fn_call_width = 80
